export const CustomEventType = {
	Frame_LOAD: 'Frame_LOAD',
	SHOW_LOADER: 'SHOW_LOADER',
	SET_ACTIVE_TOOL: 'SET_ACTIVE_TOOL',
	ON_APP_INIT: 'ON_APP_INIT',
	ADD_TRACKER: 'ADD_ANNOTATION',
	SET_ACTIVE_TRACKER: 'SET_ACTIVE_TRACKER',
	UNSET_ACTIVE_TRACKER: 'UNSET_ACTIVE_TRACKER',
	DELETE_TRACKER: 'DELETE_TRACKER',
	DELETE_TRACKER_IN_CURRENT_FRAME: 'DELETE_TRACKER_IN_CURRENT_FRAME',
	FRAME_CHANGE: 'FRAME_CHANGE',
	SET_CANVAS_DIRTY: 'SET_CANVAS_DIRTY',
	DISABLE_REVIEW_FOR_ALL_ANNOTATIONS: 'DISABLE_REVIEW_FOR_ALL_ANNOTATIONS',
	SET_FRAME_SEEKER_COMPONENT_ACTIVE_FRAME_INDEX: 'SET_FRAME_SEEKER_COMPONENT_ACTIVE_FRAME_INDEX',
	RESET_TRACKERS: 'RESET_TRACKERS'
};
